project:
  type: website
  output-dir: docs

website:
  title: "Mohan Khanal"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: R Tutorial
        href: r-tutorial/day-01-r-basics.qmd

  sidebar:
    - id: rtutorials
      title: "R Tutorial for Data Science"
      style: docked
      background: light
      contents:
        - href: r-tutorial/day-01-r-basics.qmd
          text: "Day 1: Introduction to R"
        - href: r-tutorial/day-02-data-import-wrangling.qmd
          text: "Day 2: Data Import & Wrangling"

format:
  html:
    theme: cosmo
    toc: true
