project:
  type: website

website:
  title: "Mohan Khanal"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: r-tutorial/RBasics.qmd
        text: R Tutorials
      - href: mascollelmicroeconomics/Part1.qmd
        text: Microeconomics

  sidebar:
    - id: rtutorials
      title: "R Tutorial for Data Science"
      contents:
        - r-tutorial/RBasics.qmd

    - id: micro
      title: "Mas-Colell Microeconomics"
      contents:
        - mascollelmicroeconomics/Part1.qmd

  page-navigation: true

