navbar:
  left:
    - href: index.qmd
      text: "Home"
    - sidebar: rtutorials

sidebar:
  - id: rtutorials
    title: "R Tutorial for Data Science"
    style: docked
    background: light
    contents:
      - href: r-tutorial/RBasics.qmd
        text: "Day 1: Introduction to R"
