project:
  type: website

website:
  title: "Mohan Khanal"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: r-tutorial/RBasics.qmd
        text: R Tutorials
      - href: mascollel-microeconomics/Part1.qmd
        text: Microeconomics

  sidebar:
    - id: rtutorials
      title: "R Tutorial for Data Science"
      style: docked
      background: light
      contents:
        - href: r-tutorial/RBasics.qmd
          text: "Day 1: Introduction to R"

    - id: micro
      title: "Mas-Colell Microeconomics"
      style: docked
      background: light
      contents:
        - href: mascollel-microeconomics/Part1.qmd
          text: "Part I: Chapters 1â€“4"

