project:
  type: website
  output-dir: docs

website:
  title: "Mohan Khanal"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: r-tutorial/index.qmd
        text: R Tutorial

  sidebar:
    - id: rtutorials
      title: "R Tutorial for Data Science"
      style: docked
      background: light
      contents:
        - href: r-tutorial/RBasics.qmd
          text: "Introduction to R"
        - href: r-tutorial/2DataImportandDataWrangling.qmd
          text: "Data Import & Wrangling"
        - href: r-tutorial/3ExploratoryDataAnalysis.qmd
          text: "Exploratory Data Analysis"
        - href: r-tutorial/4StatisticalAnalysis.qmd
          text: "Statistical Analysis"
        # - href: r-tutorial/5Regression.qmd
        #   text: "Regression Analysis"
        # - href: r-tutorial/6Interpretation.qmd
        #   text: "Interpretation & Reporting"

format:
  html:
    theme: cosmo
    toc: true
